require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.gitsigns"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.autocommands"
require "user.indentline"
require "user.starify"

